[package]
name = "reth-remote-exex"
version = "0.1.0"
edition = "2021"

[dependencies]
reth = { git = "https://github.com/bnmlsp/reth.git", branch = "dev-exex-internal-txs-v2.5.0", default-features = false, features = ["jemalloc", "otlp", "otlp-logs", "js-tracer", "keccak-cache-global", "asm-keccak", "min-trace-logs"] }
reth-exex = { git = "https://github.com/bnmlsp/reth.git", branch = "dev-exex-internal-txs-v2.5.0", features = ["serde"] }
reth-node-ethereum = { git = "https://github.com/bnmlsp/reth.git", branch = "dev-exex-internal-txs-v2.5.0" }
reth-node-api = { git = "https://github.com/bnmlsp/reth.git", branch = "dev-exex-internal-txs-v2.5.0" }
reth-tracing = { git = "https://github.com/bnmlsp/reth.git", branch = "dev-exex-internal-txs-v2.5.0" }
reth-execution-types = { git = "https://github.com/bnmlsp/reth.git", branch = "dev-exex-internal-txs-v2.5.0", features = ["traces"] }
reth-ethereum-primitives = { git = "https://github.com/bnmlsp/reth.git", branch = "dev-exex-internal-txs-v2.5.0" }
reth-primitives-traits = "=0.6.0"

alloy-consensus = "=2.3.0"
alloy-rpc-types-trace = "=2.3.0"
alloy-primitives = "=1.6.1"
alloy-eips = "=2.3.0"
alloy-eip2930 = "=0.2.3"
alloy-eip7702 = "=0.6.3"
revm-database = "=42.0.0"
revm-state = "=42.0.0"

tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
futures-util = "0.3"

tonic = "0.11"
prost = "0.12"

eyre = "0.6"

[build-dependencies]
tonic-build = "0.11"

[[bin]]
name = "exex"
path = "src/exex.rs"

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
